// Generated by gencpp from file vmxpi_ros/Int.msg
// DO NOT EDIT!


#ifndef VMXPI_ROS_MESSAGE_INT_H
#define VMXPI_ROS_MESSAGE_INT_H

#include <ros/service_traits.h>


#include <vmxpi_ros/IntRequest.h>
#include <vmxpi_ros/IntResponse.h>


namespace vmxpi_ros
{

struct Int
{

typedef IntRequest Request;
typedef IntResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Int
} // namespace vmxpi_ros


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::vmxpi_ros::Int > {
  static const char* value()
  {
    return "da5909fbe378aeaf85e547e830cc1bb7";
  }

  static const char* value(const ::vmxpi_ros::Int&) { return value(); }
};

template<>
struct DataType< ::vmxpi_ros::Int > {
  static const char* value()
  {
    return "vmxpi_ros/Int";
  }

  static const char* value(const ::vmxpi_ros::Int&) { return value(); }
};


// service_traits::MD5Sum< ::vmxpi_ros::IntRequest> should match
// service_traits::MD5Sum< ::vmxpi_ros::Int >
template<>
struct MD5Sum< ::vmxpi_ros::IntRequest>
{
  static const char* value()
  {
    return MD5Sum< ::vmxpi_ros::Int >::value();
  }
  static const char* value(const ::vmxpi_ros::IntRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::vmxpi_ros::IntRequest> should match
// service_traits::DataType< ::vmxpi_ros::Int >
template<>
struct DataType< ::vmxpi_ros::IntRequest>
{
  static const char* value()
  {
    return DataType< ::vmxpi_ros::Int >::value();
  }
  static const char* value(const ::vmxpi_ros::IntRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::vmxpi_ros::IntResponse> should match
// service_traits::MD5Sum< ::vmxpi_ros::Int >
template<>
struct MD5Sum< ::vmxpi_ros::IntResponse>
{
  static const char* value()
  {
    return MD5Sum< ::vmxpi_ros::Int >::value();
  }
  static const char* value(const ::vmxpi_ros::IntResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::vmxpi_ros::IntResponse> should match
// service_traits::DataType< ::vmxpi_ros::Int >
template<>
struct DataType< ::vmxpi_ros::IntResponse>
{
  static const char* value()
  {
    return DataType< ::vmxpi_ros::Int >::value();
  }
  static const char* value(const ::vmxpi_ros::IntResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // VMXPI_ROS_MESSAGE_INT_H
