// Generated by gencpp from file vmxpi_ros/IntRes.msg
// DO NOT EDIT!


#ifndef VMXPI_ROS_MESSAGE_INTRES_H
#define VMXPI_ROS_MESSAGE_INTRES_H

#include <ros/service_traits.h>


#include <vmxpi_ros/IntResRequest.h>
#include <vmxpi_ros/IntResResponse.h>


namespace vmxpi_ros
{

struct IntRes
{

typedef IntResRequest Request;
typedef IntResResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct IntRes
} // namespace vmxpi_ros


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::vmxpi_ros::IntRes > {
  static const char* value()
  {
    return "8524586e34fbd7cb1c08c5f5f1ca0e57";
  }

  static const char* value(const ::vmxpi_ros::IntRes&) { return value(); }
};

template<>
struct DataType< ::vmxpi_ros::IntRes > {
  static const char* value()
  {
    return "vmxpi_ros/IntRes";
  }

  static const char* value(const ::vmxpi_ros::IntRes&) { return value(); }
};


// service_traits::MD5Sum< ::vmxpi_ros::IntResRequest> should match
// service_traits::MD5Sum< ::vmxpi_ros::IntRes >
template<>
struct MD5Sum< ::vmxpi_ros::IntResRequest>
{
  static const char* value()
  {
    return MD5Sum< ::vmxpi_ros::IntRes >::value();
  }
  static const char* value(const ::vmxpi_ros::IntResRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::vmxpi_ros::IntResRequest> should match
// service_traits::DataType< ::vmxpi_ros::IntRes >
template<>
struct DataType< ::vmxpi_ros::IntResRequest>
{
  static const char* value()
  {
    return DataType< ::vmxpi_ros::IntRes >::value();
  }
  static const char* value(const ::vmxpi_ros::IntResRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::vmxpi_ros::IntResResponse> should match
// service_traits::MD5Sum< ::vmxpi_ros::IntRes >
template<>
struct MD5Sum< ::vmxpi_ros::IntResResponse>
{
  static const char* value()
  {
    return MD5Sum< ::vmxpi_ros::IntRes >::value();
  }
  static const char* value(const ::vmxpi_ros::IntResResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::vmxpi_ros::IntResResponse> should match
// service_traits::DataType< ::vmxpi_ros::IntRes >
template<>
struct DataType< ::vmxpi_ros::IntResResponse>
{
  static const char* value()
  {
    return DataType< ::vmxpi_ros::IntRes >::value();
  }
  static const char* value(const ::vmxpi_ros::IntResResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // VMXPI_ROS_MESSAGE_INTRES_H
