// Generated by gencpp from file vmxpi_ros/LimitSwitch.msg
// DO NOT EDIT!


#ifndef VMXPI_ROS_MESSAGE_LIMITSWITCH_H
#define VMXPI_ROS_MESSAGE_LIMITSWITCH_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace vmxpi_ros
{
template <class ContainerAllocator>
struct LimitSwitch_
{
  typedef LimitSwitch_<ContainerAllocator> Type;

  LimitSwitch_()
    : limitswitch()  {
    }
  LimitSwitch_(const ContainerAllocator& _alloc)
    : limitswitch(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<uint8_t, typename ContainerAllocator::template rebind<uint8_t>::other >  _limitswitch_type;
  _limitswitch_type limitswitch;





  typedef boost::shared_ptr< ::vmxpi_ros::LimitSwitch_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::vmxpi_ros::LimitSwitch_<ContainerAllocator> const> ConstPtr;

}; // struct LimitSwitch_

typedef ::vmxpi_ros::LimitSwitch_<std::allocator<void> > LimitSwitch;

typedef boost::shared_ptr< ::vmxpi_ros::LimitSwitch > LimitSwitchPtr;
typedef boost::shared_ptr< ::vmxpi_ros::LimitSwitch const> LimitSwitchConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::vmxpi_ros::LimitSwitch_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::vmxpi_ros::LimitSwitch_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::vmxpi_ros::LimitSwitch_<ContainerAllocator1> & lhs, const ::vmxpi_ros::LimitSwitch_<ContainerAllocator2> & rhs)
{
  return lhs.limitswitch == rhs.limitswitch;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::vmxpi_ros::LimitSwitch_<ContainerAllocator1> & lhs, const ::vmxpi_ros::LimitSwitch_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace vmxpi_ros

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::vmxpi_ros::LimitSwitch_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::vmxpi_ros::LimitSwitch_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::vmxpi_ros::LimitSwitch_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::vmxpi_ros::LimitSwitch_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::vmxpi_ros::LimitSwitch_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::vmxpi_ros::LimitSwitch_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::vmxpi_ros::LimitSwitch_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cabe49bdbfdd4a3cf170660bf17038a4";
  }

  static const char* value(const ::vmxpi_ros::LimitSwitch_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xcabe49bdbfdd4a3cULL;
  static const uint64_t static_value2 = 0xf170660bf17038a4ULL;
};

template<class ContainerAllocator>
struct DataType< ::vmxpi_ros::LimitSwitch_<ContainerAllocator> >
{
  static const char* value()
  {
    return "vmxpi_ros/LimitSwitch";
  }

  static const char* value(const ::vmxpi_ros::LimitSwitch_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::vmxpi_ros::LimitSwitch_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool[] limitswitch\n"
;
  }

  static const char* value(const ::vmxpi_ros::LimitSwitch_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::vmxpi_ros::LimitSwitch_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.limitswitch);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct LimitSwitch_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::vmxpi_ros::LimitSwitch_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::vmxpi_ros::LimitSwitch_<ContainerAllocator>& v)
  {
    s << indent << "limitswitch[]" << std::endl;
    for (size_t i = 0; i < v.limitswitch.size(); ++i)
    {
      s << indent << "  limitswitch[" << i << "]: ";
      Printer<uint8_t>::stream(s, indent + "  ", v.limitswitch[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // VMXPI_ROS_MESSAGE_LIMITSWITCH_H
