// Generated by gencpp from file vmxpi_ros/MotorSpeed.msg
// DO NOT EDIT!


#ifndef VMXPI_ROS_MESSAGE_MOTORSPEED_H
#define VMXPI_ROS_MESSAGE_MOTORSPEED_H

#include <ros/service_traits.h>


#include <vmxpi_ros/MotorSpeedRequest.h>
#include <vmxpi_ros/MotorSpeedResponse.h>


namespace vmxpi_ros
{

struct MotorSpeed
{

typedef MotorSpeedRequest Request;
typedef MotorSpeedResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct MotorSpeed
} // namespace vmxpi_ros


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::vmxpi_ros::MotorSpeed > {
  static const char* value()
  {
    return "c74fe58695fd9150f0fc1ab8000015b6";
  }

  static const char* value(const ::vmxpi_ros::MotorSpeed&) { return value(); }
};

template<>
struct DataType< ::vmxpi_ros::MotorSpeed > {
  static const char* value()
  {
    return "vmxpi_ros/MotorSpeed";
  }

  static const char* value(const ::vmxpi_ros::MotorSpeed&) { return value(); }
};


// service_traits::MD5Sum< ::vmxpi_ros::MotorSpeedRequest> should match
// service_traits::MD5Sum< ::vmxpi_ros::MotorSpeed >
template<>
struct MD5Sum< ::vmxpi_ros::MotorSpeedRequest>
{
  static const char* value()
  {
    return MD5Sum< ::vmxpi_ros::MotorSpeed >::value();
  }
  static const char* value(const ::vmxpi_ros::MotorSpeedRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::vmxpi_ros::MotorSpeedRequest> should match
// service_traits::DataType< ::vmxpi_ros::MotorSpeed >
template<>
struct DataType< ::vmxpi_ros::MotorSpeedRequest>
{
  static const char* value()
  {
    return DataType< ::vmxpi_ros::MotorSpeed >::value();
  }
  static const char* value(const ::vmxpi_ros::MotorSpeedRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::vmxpi_ros::MotorSpeedResponse> should match
// service_traits::MD5Sum< ::vmxpi_ros::MotorSpeed >
template<>
struct MD5Sum< ::vmxpi_ros::MotorSpeedResponse>
{
  static const char* value()
  {
    return MD5Sum< ::vmxpi_ros::MotorSpeed >::value();
  }
  static const char* value(const ::vmxpi_ros::MotorSpeedResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::vmxpi_ros::MotorSpeedResponse> should match
// service_traits::DataType< ::vmxpi_ros::MotorSpeed >
template<>
struct DataType< ::vmxpi_ros::MotorSpeedResponse>
{
  static const char* value()
  {
    return DataType< ::vmxpi_ros::MotorSpeed >::value();
  }
  static const char* value(const ::vmxpi_ros::MotorSpeedResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // VMXPI_ROS_MESSAGE_MOTORSPEED_H
