// Generated by gencpp from file vmxpi_ros/StopModeResponse.msg
// DO NOT EDIT!


#ifndef VMXPI_ROS_MESSAGE_STOPMODERESPONSE_H
#define VMXPI_ROS_MESSAGE_STOPMODERESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace vmxpi_ros
{
template <class ContainerAllocator>
struct StopModeResponse_
{
  typedef StopModeResponse_<ContainerAllocator> Type;

  StopModeResponse_()
    {
    }
  StopModeResponse_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::vmxpi_ros::StopModeResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::vmxpi_ros::StopModeResponse_<ContainerAllocator> const> ConstPtr;

}; // struct StopModeResponse_

typedef ::vmxpi_ros::StopModeResponse_<std::allocator<void> > StopModeResponse;

typedef boost::shared_ptr< ::vmxpi_ros::StopModeResponse > StopModeResponsePtr;
typedef boost::shared_ptr< ::vmxpi_ros::StopModeResponse const> StopModeResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::vmxpi_ros::StopModeResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::vmxpi_ros::StopModeResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


} // namespace vmxpi_ros

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::vmxpi_ros::StopModeResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::vmxpi_ros::StopModeResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::vmxpi_ros::StopModeResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::vmxpi_ros::StopModeResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::vmxpi_ros::StopModeResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::vmxpi_ros::StopModeResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::vmxpi_ros::StopModeResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::vmxpi_ros::StopModeResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::vmxpi_ros::StopModeResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "vmxpi_ros/StopModeResponse";
  }

  static const char* value(const ::vmxpi_ros::StopModeResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::vmxpi_ros::StopModeResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
;
  }

  static const char* value(const ::vmxpi_ros::StopModeResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::vmxpi_ros::StopModeResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct StopModeResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::vmxpi_ros::StopModeResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::vmxpi_ros::StopModeResponse_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // VMXPI_ROS_MESSAGE_STOPMODERESPONSE_H
