// Generated by gencpp from file vmxpi_ros/StopModeRequest.msg
// DO NOT EDIT!


#ifndef VMXPI_ROS_MESSAGE_STOPMODEREQUEST_H
#define VMXPI_ROS_MESSAGE_STOPMODEREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace vmxpi_ros
{
template <class ContainerAllocator>
struct StopModeRequest_
{
  typedef StopModeRequest_<ContainerAllocator> Type;

  StopModeRequest_()
    : motor(0)
    , mode(0)  {
    }
  StopModeRequest_(const ContainerAllocator& _alloc)
    : motor(0)
    , mode(0)  {
  (void)_alloc;
    }



   typedef int8_t _motor_type;
  _motor_type motor;

   typedef int8_t _mode_type;
  _mode_type mode;





  typedef boost::shared_ptr< ::vmxpi_ros::StopModeRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::vmxpi_ros::StopModeRequest_<ContainerAllocator> const> ConstPtr;

}; // struct StopModeRequest_

typedef ::vmxpi_ros::StopModeRequest_<std::allocator<void> > StopModeRequest;

typedef boost::shared_ptr< ::vmxpi_ros::StopModeRequest > StopModeRequestPtr;
typedef boost::shared_ptr< ::vmxpi_ros::StopModeRequest const> StopModeRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::vmxpi_ros::StopModeRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::vmxpi_ros::StopModeRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::vmxpi_ros::StopModeRequest_<ContainerAllocator1> & lhs, const ::vmxpi_ros::StopModeRequest_<ContainerAllocator2> & rhs)
{
  return lhs.motor == rhs.motor &&
    lhs.mode == rhs.mode;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::vmxpi_ros::StopModeRequest_<ContainerAllocator1> & lhs, const ::vmxpi_ros::StopModeRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace vmxpi_ros

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::vmxpi_ros::StopModeRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::vmxpi_ros::StopModeRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::vmxpi_ros::StopModeRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::vmxpi_ros::StopModeRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::vmxpi_ros::StopModeRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::vmxpi_ros::StopModeRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::vmxpi_ros::StopModeRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f4be1905b0e869ab5f98286edb652845";
  }

  static const char* value(const ::vmxpi_ros::StopModeRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf4be1905b0e869abULL;
  static const uint64_t static_value2 = 0x5f98286edb652845ULL;
};

template<class ContainerAllocator>
struct DataType< ::vmxpi_ros::StopModeRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "vmxpi_ros/StopModeRequest";
  }

  static const char* value(const ::vmxpi_ros::StopModeRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::vmxpi_ros::StopModeRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int8 motor\n"
"int8 mode\n"
;
  }

  static const char* value(const ::vmxpi_ros::StopModeRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::vmxpi_ros::StopModeRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.motor);
      stream.next(m.mode);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct StopModeRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::vmxpi_ros::StopModeRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::vmxpi_ros::StopModeRequest_<ContainerAllocator>& v)
  {
    s << indent << "motor: ";
    Printer<int8_t>::stream(s, indent + "  ", v.motor);
    s << indent << "mode: ";
    Printer<int8_t>::stream(s, indent + "  ", v.mode);
  }
};

} // namespace message_operations
} // namespace ros

#endif // VMXPI_ROS_MESSAGE_STOPMODEREQUEST_H
