// Generated by gencpp from file vmxpi_ros/StringRes.msg
// DO NOT EDIT!


#ifndef VMXPI_ROS_MESSAGE_STRINGRES_H
#define VMXPI_ROS_MESSAGE_STRINGRES_H

#include <ros/service_traits.h>


#include <vmxpi_ros/StringResRequest.h>
#include <vmxpi_ros/StringResResponse.h>


namespace vmxpi_ros
{

struct StringRes
{

typedef StringResRequest Request;
typedef StringResResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct StringRes
} // namespace vmxpi_ros


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::vmxpi_ros::StringRes > {
  static const char* value()
  {
    return "992ce8a1687cec8c8bd883ec73ca41d1";
  }

  static const char* value(const ::vmxpi_ros::StringRes&) { return value(); }
};

template<>
struct DataType< ::vmxpi_ros::StringRes > {
  static const char* value()
  {
    return "vmxpi_ros/StringRes";
  }

  static const char* value(const ::vmxpi_ros::StringRes&) { return value(); }
};


// service_traits::MD5Sum< ::vmxpi_ros::StringResRequest> should match
// service_traits::MD5Sum< ::vmxpi_ros::StringRes >
template<>
struct MD5Sum< ::vmxpi_ros::StringResRequest>
{
  static const char* value()
  {
    return MD5Sum< ::vmxpi_ros::StringRes >::value();
  }
  static const char* value(const ::vmxpi_ros::StringResRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::vmxpi_ros::StringResRequest> should match
// service_traits::DataType< ::vmxpi_ros::StringRes >
template<>
struct DataType< ::vmxpi_ros::StringResRequest>
{
  static const char* value()
  {
    return DataType< ::vmxpi_ros::StringRes >::value();
  }
  static const char* value(const ::vmxpi_ros::StringResRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::vmxpi_ros::StringResResponse> should match
// service_traits::MD5Sum< ::vmxpi_ros::StringRes >
template<>
struct MD5Sum< ::vmxpi_ros::StringResResponse>
{
  static const char* value()
  {
    return MD5Sum< ::vmxpi_ros::StringRes >::value();
  }
  static const char* value(const ::vmxpi_ros::StringResResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::vmxpi_ros::StringResResponse> should match
// service_traits::DataType< ::vmxpi_ros::StringRes >
template<>
struct DataType< ::vmxpi_ros::StringResResponse>
{
  static const char* value()
  {
    return DataType< ::vmxpi_ros::StringRes >::value();
  }
  static const char* value(const ::vmxpi_ros::StringResResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // VMXPI_ROS_MESSAGE_STRINGRES_H
